[package]
name = "client"
version = "0.1.0"
edition = "2021"


[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = "0.11.10"
serde = { version = "1.0.137", features = ["derive"] }

human-panic = "1.0.3"
pretty_env_logger = "0.4.0"
clap = { version = "3.1.18", features = ["derive", "color", "suggestions", "termcolor", "wrap_help"] }