[package]
name = "client"
version = "0.1.0"
edition = "2021"


[dependencies]
tokio = { version = "1", features = ["full"] }
futures = "0.3.21"

warp = "0.3.2"
serde = { version = "1.0.137", features = ["derive"] }
bincode = "1.3.3"

reqwest = { version = "0.11.10", features = ["json"]}


human-panic = "1.0.3"
log = "0.4.17"
pretty_env_logger = "0.4.0"
clap = { version = "3.1.18", features = ["derive", "color", "suggestions", "termcolor", "wrap_help"] }