FROM lukemathwalker/cargo-chef:latest-rust-alpine AS chef
WORKDIR /app

RUN apk upgrade --update-cache --available && apk add openssl openssl-dev pkgconfig

FROM chef as planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder
COPY --from=planner /app/recipe.json recipe.json
RUN cargo chef cook --recipe-path recipe.json

# Build application
COPY . .
RUN cargo build

# We do not need the Rust toolchain to run the binary!
FROM alpine AS runtime
WORKDIR /app
COPY --from=builder /app/target/debug/syncabull /app/

ENV HOST 0.0.0.0
ENV PORT 3000

EXPOSE 3000

CMD [ "/app/syncabull" ]
