[package]
name = "syncabull"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oauth2 = "4.2.0"
tokio = { version = "1", features = ["full"] }
warp = { version = "0.3.2", features = ["multipart", "tls"] }
futures = "0.3.21"
reqwest = "0.11.10"
serde = { version = "1.0.137", features = ["derive"] }