FROM lukemathwalker/cargo-chef:latest-rust-1 AS chef
WORKDIR /app

RUN apt-get update && apt-get install -y openssl libssl-dev pkg-config

FROM chef as planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder
COPY --from=planner /app/recipe.json recipe.json
RUN cargo chef cook --recipe-path recipe.json --bin syncabull_api

# Build application
COPY . .
RUN cargo build --bin syncabull_api

# We do not need the Rust toolchain to run the binary!
FROM debian:buster-slim AS runtime
RUN apt-get update && apt-get install -y openssl ca-certificates

WORKDIR /app
COPY --from=builder /app/target/debug/syncabull_api /app/
COPY --from=builder /app/api/www/dynamic/* /app/www/dynamic/

ENV HOST 0.0.0.0
ENV PORT 3000

EXPOSE ${PORT}

CMD [ "/app/syncabull_api" ]
