version: '3'

services:

  traefik:
    container_name: traefik
    image: traefik:v2.5
    privileged: true
    depends_on:
      - api
      - frontend
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.filename=/etc/traefik/traefik-dynamic.yml

      # Let's Encrypt
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=${LETSENCRYPT_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json

      # Listen for https on 443, and http on 80 which just redirects to https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls.certresolver=letsencrypt
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      
    ports:
      - 443:443
      - 80:80
      - 127.0.0.1:9091:8080

    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik-dynamic.yml:/etc/traefik/traefik-dynamic.yml

  frontend:
    container_name: frontend
    build: ./app
    restart: always
    depends_on:
      - api
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - BROWSER_BASE_URL=https://${DOMAIN}
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.frontend.entrypoints=websecure
      - traefik.http.routers.frontend.middlewares=security-headers@file

  api:
    container_name: api
    build: ./api
    restart: always
    depends_on:
      - db
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=syncabull
      - DB_USER=syncabull
      - DB_PASS=${DB_PASS}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - BROWSER_BASE_URL=https://${DOMAIN}
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`${DOMAIN}`) && PathPrefix(`/api`)
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.routers.api.middlewares=security-headers@file, api-headers@file

  db:
    container_name: db
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=syncabull
      - POSTGRES_USER=syncabull
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - syncabull-pgdata:/var/lib/postgresql/data

volumes:
  syncabull-pgdata:
    external: true