---
name: pre-release

on:
  push:
    branches:
      - main

jobs:
  tagged-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
      packages: write
      deployments: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install upx
        run: sudo apt-get install upx

      - name: Install nightly toolchain
        run: |
          rustup toolchain install nightly
          rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu

      - name: Build Project
        run: cargo +nightly build -Z build-std=std,panic_abort --target x86_64-unknown-linux-gnu --profile production

      - name: Compress Project
        run: |
          upx --lzma --best target/x86_64-unknown-linux-gnu/production/syncabull
          upx --lzma --best target/x86_64-unknown-linux-gnu/production/syncabull_api
          mv target/x86_64-unknown-linux-gnu/production/syncabull_api api
          mv target/x86_64-unknown-linux-gnu/production/syncabull cli

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: "dev"
          title: "Dev Build"
          files: |
            license
            readme.md
            cli
            api

      - name: Run latest-tag
        uses: EndBug/latest-tag@latest
        with:
          ref: latest
          description: The latest release for the application
          force-branch: false
